export const bastionCar = [
    {
        "cardCode": "000028F72FF4",
        "personData": {
            "personId": 18202,
            "name": "HYUNDAI SOLARIS",
            "firstName": "Y487OH116",
            "secondName": "",
            "tableNo": "18202",
            "personCat": "4 Транспорт",
            "org": "ООО ИТЦ Гардиан",
            "dep": "ООО ИТЦ Гардиан",
            "post": "Личный автотранспорт",
            "comments": "САГД 385040",
            "docIssueOrgan": "",
            "docSer": "",
            "docNo": "",
            "docIssueDate": null,
            "birthDate": "1901-01-01T00:00:00+05:00",
            "birthPlace": "",
            "address": "",
            "phone": "",
            "foto": null,
            "addField1": "Вохрин А.Ю.",
            "addField2": "",
            "addField3": "",
            "addField4": "",
            "addField5": "",
            "addField6": "",
            "addField7": "*******Т",
            "addField8": "",
            "addField9": "",
            "addField10": "",
            "addField11": "",
            "addField12": "",
            "addField13": "У487ОН116",
            "addField14": "HYUNDAI SOLARIS",
            "addField15": "У487ОН116",
            "addField16": "",
            "addField17": "",
            "addField18": "Автомобиль личный",
            "addField19": "",
            "addField20": "",
            "createDate": "2025-04-22T00:26:15+05:00",
            "docType": "",
            "citizenship": "",
            "email": "",
            "gender": null,
            "changeDate": null
        },
        "passType": 1,
        "dateFrom": "2024-02-02T02:00:00+05:00",
        "dateTo": "2026-01-02T01:59:59+05:00",
        "cardStatus": 1,
        "timeInterval": null,
        "entryPoints": [],
        "accessLevels": [
            {
                "servID": "SRV1",
                "id": 240,
                "name": "Проезд К легковые подряд. орг. 2 ЗОНА"
            }
        ],
        "passCat": "",
        "createDate": "2025-04-22T00:26:15+05:00",
        "issueDate": "2025-04-22T00:26:15+05:00",
        "pincode": "",
        "isBlocked": false,
        "blockedReason": "",
        "changeDate": null
    }
]